version : '2'

services:
  springappserver:
    build:
      context: .
      dockerfile: kamienica.dockerfile
    ports:
      - "8080:8081"
    networks:
      - net-spring-db
    volumes:
      - .:/vol/development
    depends_on:
      - mysqldbserver

  mysqldbserver:
    build:
      context: .
      dockerfile: mysqldb.dockerfile
    ports:
      - "3306:3307"
    networks:
      - net-spring-db
    environment:
      MYSQL_DATABASE: kamienica
      MYSQL_USER: root
      MYSQL_PASSWORD: maciej
      MYSQL_ROOT_PASSWORD: maciej
    container_name: mysqldbserver

networks:
  net-spring-db:
    driver: bridge